# Nombre de la aplicación
spring.application.name=backend

# Configuración de la Base de Datos H2 en Memoria
spring.datasource.url=jdbc:h2:mem:reportesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permitir que Hibernate cree y actualice las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Activar la Consola Web de H2 (para ver los datos en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
